export const SET_USER='setUser'
export const REMOVE_USER='removeUser'
export const GET_TAGS='getTags'
export const SET_TAGS='setTags'
export const SHOW_LOGIN_MODEL='showLoginModel'
export const SHOW_REGISTER_MODEL='showRegisterModel'